require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LostFoundsController do

  # This should return the minimal set of attributes required to create a valid
  # LostFound. As you add validations to LostFound, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LostFoundsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lost_founds as @lost_founds" do
      lost_found = LostFound.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lost_founds).should eq([lost_found])
    end
  end

  describe "GET show" do
    it "assigns the requested lost_found as @lost_found" do
      lost_found = LostFound.create! valid_attributes
      get :show, {:id => lost_found.to_param}, valid_session
      assigns(:lost_found).should eq(lost_found)
    end
  end

  describe "GET new" do
    it "assigns a new lost_found as @lost_found" do
      get :new, {}, valid_session
      assigns(:lost_found).should be_a_new(LostFound)
    end
  end

  describe "GET edit" do
    it "assigns the requested lost_found as @lost_found" do
      lost_found = LostFound.create! valid_attributes
      get :edit, {:id => lost_found.to_param}, valid_session
      assigns(:lost_found).should eq(lost_found)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LostFound" do
        expect {
          post :create, {:lost_found => valid_attributes}, valid_session
        }.to change(LostFound, :count).by(1)
      end

      it "assigns a newly created lost_found as @lost_found" do
        post :create, {:lost_found => valid_attributes}, valid_session
        assigns(:lost_found).should be_a(LostFound)
        assigns(:lost_found).should be_persisted
      end

      it "redirects to the created lost_found" do
        post :create, {:lost_found => valid_attributes}, valid_session
        response.should redirect_to(LostFound.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lost_found as @lost_found" do
        # Trigger the behavior that occurs when invalid params are submitted
        LostFound.any_instance.stub(:save).and_return(false)
        post :create, {:lost_found => {}}, valid_session
        assigns(:lost_found).should be_a_new(LostFound)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LostFound.any_instance.stub(:save).and_return(false)
        post :create, {:lost_found => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lost_found" do
        lost_found = LostFound.create! valid_attributes
        # Assuming there are no other lost_founds in the database, this
        # specifies that the LostFound created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LostFound.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => lost_found.to_param, :lost_found => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested lost_found as @lost_found" do
        lost_found = LostFound.create! valid_attributes
        put :update, {:id => lost_found.to_param, :lost_found => valid_attributes}, valid_session
        assigns(:lost_found).should eq(lost_found)
      end

      it "redirects to the lost_found" do
        lost_found = LostFound.create! valid_attributes
        put :update, {:id => lost_found.to_param, :lost_found => valid_attributes}, valid_session
        response.should redirect_to(lost_found)
      end
    end

    describe "with invalid params" do
      it "assigns the lost_found as @lost_found" do
        lost_found = LostFound.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LostFound.any_instance.stub(:save).and_return(false)
        put :update, {:id => lost_found.to_param, :lost_found => {}}, valid_session
        assigns(:lost_found).should eq(lost_found)
      end

      it "re-renders the 'edit' template" do
        lost_found = LostFound.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LostFound.any_instance.stub(:save).and_return(false)
        put :update, {:id => lost_found.to_param, :lost_found => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lost_found" do
      lost_found = LostFound.create! valid_attributes
      expect {
        delete :destroy, {:id => lost_found.to_param}, valid_session
      }.to change(LostFound, :count).by(-1)
    end

    it "redirects to the lost_founds list" do
      lost_found = LostFound.create! valid_attributes
      delete :destroy, {:id => lost_found.to_param}, valid_session
      response.should redirect_to(lost_founds_url)
    end
  end

end
